import type { DigestData } from "./types.js";

/** Sample issue used by the preview script and the snapshot test. */
export const sampleDigest: DigestData = {
  dateLabel: "Tuesday, September 8",
  greeting: "Good morning.",
  steepedFor: "23h 40m",
  streakDays: 12,
  totalStories: 13,
  readMinutes: 4,
  topics: [
    {
      id: "t-tech",
      name: "Technology",
      accent: "#2563EB",
      moreUrl: "https://steep.example/f/more-tech",
      lessUrl: "https://steep.example/f/less-tech",
      stories: [
        {
          id: "s1",
          title: "Apple’s new MacBook Pro has a 24-hour battery and an M5 chip",
          url: "https://steep.example/r/s1",
          source: "The Verge",
          timeAgo: "3h ago",
          snippet:
            "Apple has announced the M5 MacBook Pro, and the headline feature is a battery that Apple says lasts a full day of mixed use. The new chip is built on a 2nm process and brings a lot more GPU cores…",
          imageUrl: "https://picsum.photos/seed/steep-lead/1200/630",
          clusterSize: 4,
        },
        {
          id: "s2",
          title: "Microsoft says virtually nobody was grabbing NYT articles through its chatbot",
          url: "https://steep.example/r/s2",
          source: "The Verge",
          timeAgo: "5h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
        {
          id: "s3",
          title: "Automakers urge Congress to permanently ban Chinese connected vehicles",
          url: "https://steep.example/r/s3",
          source: "CNBC",
          timeAgo: "6h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 3,
        },
        {
          id: "s4",
          title: "Waymo expands to Denver after a winter of testing on ice",
          url: "https://steep.example/r/s4",
          source: "Ars Technica",
          timeAgo: "9h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
        {
          id: "s5",
          title: "The White House is making arcade games racist",
          url: "https://steep.example/r/s5",
          source: "TechCrunch",
          timeAgo: "14h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
      ],
    },
    {
      id: "t-world",
      name: "World",
      accent: "#B42318",
      moreUrl: "https://steep.example/f/more-world",
      lessUrl: "https://steep.example/f/less-world",
      stories: [
        {
          id: "w1",
          title: "UN votes to adopt new world map that reflects Africa’s true size",
          url: "https://steep.example/r/w1",
          source: "BBC World",
          timeAgo: "2h ago",
          snippet:
            "The General Assembly backed a resolution to replace the Mercator projection in UN materials, ending a decades-long argument about how the continent is drawn.",
          imageUrl: "https://picsum.photos/seed/steep-world/1200/630",
          clusterSize: 3,
        },
        {
          id: "w2",
          title: "Argentina escalates Falklands dispute with the U.K., seizing on Trump comments",
          url: "https://steep.example/r/w2",
          source: "NPR World",
          timeAgo: "4h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
        {
          id: "w3",
          title: "Typhoon Halong makes landfall in Vietnam as thousands evacuate",
          url: "https://steep.example/r/w3",
          source: "Al Jazeera",
          timeAgo: "7h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
        {
          id: "w4",
          title: "France’s new prime minister survives first confidence vote",
          url: "https://steep.example/r/w4",
          source: "BBC World",
          timeAgo: "11h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
      ],
    },
    {
      id: "t-f1",
      name: "Formula 1",
      accent: "#0F766E",
      moreUrl: "https://steep.example/f/more-f1",
      lessUrl: "https://steep.example/f/less-f1",
      stories: [
        {
          id: "f1",
          title: "Norris takes Monza pole by 0.04s as McLaren lock out the front row",
          url: "https://steep.example/r/f1",
          source: "The Race",
          timeAgo: "1h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 2,
        },
        {
          id: "f2",
          title: "Ferrari confirm 2027 driver line-up ahead of home race",
          url: "https://steep.example/r/f2",
          source: "Motorsport.com",
          timeAgo: "3h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
        {
          id: "f3",
          title: "Why the new 2026 engines are still catching teams out",
          url: "https://steep.example/r/f3",
          source: "Autosport",
          timeAgo: "8h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
        {
          id: "f4",
          title: "Stroll to miss Baku with wrist injury; Drugovich steps in",
          url: "https://steep.example/r/f4",
          source: "ESPN",
          timeAgo: "10h ago",
          snippet: null,
          imageUrl: null,
          clusterSize: 1,
        },
      ],
    },
  ],
  quietTopics: ["Science"],
  suggestions: [
    { name: "Business", url: "https://steep.example/topics?add=business" },
    { name: "Health", url: "https://steep.example/topics?add=health" },
    { name: "NBA", url: "https://steep.example/topics?add=nba" },
  ],
  links: {
    manage: "https://steep.example/topics",
    viewInBrowser: "https://steep.example/d/abc",
    unsubscribe: "https://steep.example/unsubscribe/xyz",
  },
  sentAtLabel: "7:00 AM Toronto time",
};
